#!/usr/bin/env python3.8
# @generated by pegen from meta.gram

import ast
import sys
import tokenize

from typing import Any, Optional

from pegen.parser import memoize, memoize_left_rec, logger, Parser

from meta_ast import *

# Keywords and soft keywords are listed at the end of the parser definition.
class MetaParser(Parser):

    @memoize
    def start(self) -> Optional[Any]:
        # start: rule+ $
        mark = self._mark()
        if (
            (a := self._loop1_1())
            and
            (self.expect('ENDMARKER'))
        ):
            return Grammar ( a );
        self._reset(mark)
        return None;

    @memoize
    def rule(self) -> Optional[Any]:
        # rule: NAME '=' choice
        mark = self._mark()
        if (
            (a := self.name())
            and
            (self.expect('='))
            and
            (b := self.choice())
        ):
            return Rule ( a . string , b );
        self._reset(mark)
        return None;

    @memoize
    def choice(self) -> Optional[Any]:
        # choice: sequence (('|' sequence))*
        mark = self._mark()
        if (
            (a := self.sequence())
            and
            (b := self._loop0_2(),)
        ):
            return Choice ( c ) if ( c := ( [a] + [i [1] for i in b] ) ) and len ( c ) > 1 else c [0];
        self._reset(mark)
        return None;

    @memoize
    def sequence(self) -> Optional[Any]:
        # sequence: item+
        mark = self._mark()
        if (
            (a := self._loop1_3())
        ):
            return Sequence ( a ) if len ( a ) > 1 else a [0];
        self._reset(mark)
        return None;

    @memoize
    def item(self) -> Optional[Any]:
        # item: '{' choice '}' | '[' choice ']' | NAME !'=' | STRING
        mark = self._mark()
        if (
            (self.expect('{'))
            and
            (a := self.choice())
            and
            (self.expect('}'))
        ):
            return Repeat ( a );
        self._reset(mark)
        if (
            (self.expect('['))
            and
            (a := self.choice())
            and
            (self.expect(']'))
        ):
            return Option ( a );
        self._reset(mark)
        if (
            (a := self.name())
            and
            (self.negative_lookahead(self.expect, '='))
        ):
            return Name ( a . string );
        self._reset(mark)
        if (
            (a := self.string())
        ):
            return String ( a . string );
        self._reset(mark)
        return None;

    @memoize
    def _loop1_1(self) -> Optional[Any]:
        # _loop1_1: rule
        mark = self._mark()
        children = []
        while (
            (rule := self.rule())
        ):
            children.append(rule)
            mark = self._mark()
        self._reset(mark)
        return children;

    @memoize
    def _loop0_2(self) -> Optional[Any]:
        # _loop0_2: ('|' sequence)
        mark = self._mark()
        children = []
        while (
            (_tmp_4 := self._tmp_4())
        ):
            children.append(_tmp_4)
            mark = self._mark()
        self._reset(mark)
        return children;

    @memoize
    def _loop1_3(self) -> Optional[Any]:
        # _loop1_3: item
        mark = self._mark()
        children = []
        while (
            (item := self.item())
        ):
            children.append(item)
            mark = self._mark()
        self._reset(mark)
        return children;

    @memoize
    def _tmp_4(self) -> Optional[Any]:
        # _tmp_4: '|' sequence
        mark = self._mark()
        if (
            (literal := self.expect('|'))
            and
            (sequence := self.sequence())
        ):
            return [literal, sequence];
        self._reset(mark)
        return None;

    KEYWORDS = ()
    SOFT_KEYWORDS = ()


if __name__ == '__main__':
    from pegen.parser import simple_parser_main
    simple_parser_main(MetaParser)
